apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jouni609/MOOC-Kubernetes-Submissions.git
    targetRevision: HEAD
    path: 4.7/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: exercises
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
