apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jouni609/MOOC-Kubernetes-Submissions.git
    targetRevision: HEAD
    path: "4.8"
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
