apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - Log_Output/manifests/deployment.yaml
  - Log_Output/manifests/service.yaml
  - Ping_Pong/manifests/knative-service.yaml
  - Ping_Pong/manifests/postgres-service.yaml
  - Ping_Pong/manifests/postgres-statefulset.yaml

secretGenerator:
  - name: postgres-secret
    namespace: exercises
    literals:
      - POSTGRES_PASSWORD=postgres

generatorOptions:
  disableNameSuffixHash: true
