apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: log-output:2.3
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: PINGPONG_URL
              value: "http://pingpong-svc:2345/pongs"
          ports:
            - containerPort: 3000
