apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: dwk-pvc
      containers:
        - name: landingpage
          image: landingpage:1.12
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
