apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jouni609/MOOC410CONFIG.git
    targetRevision: "4.10"
    path: overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
