apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Todo_App/manifests/configmap.yaml
  - Todo_App/manifests/deployment.yaml
  - Todo_App/manifests/service.yaml
  - Todo_App/manifests/pvc.yaml
  - Todo_Backend/manifests/configmap.yaml
  - Todo_Backend/manifests/deployment.yaml
  - Todo_Backend/manifests/service.yaml
  - Todo_Backend/manifests/postgres-service.yaml
  - Todo_Backend/manifests/postgres-statefulset.yaml
  - Todo_Backend/manifests/secret.yaml
  - Todo_Job/manifests/cronjob.yaml
  - manifests/gateway.yaml
  - manifests/httproute.yaml

images:
  - name: todo-app
    newName: todo-app
    newTag: local
  - name: todo-backend
    newName: todo-backend
    newTag: local
  - name: todo-job
    newName: todo-job
    newTag: local
