apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: log-output:5.3
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: GREETER_URL
              value: "http://greeter-svc:8080/"
          ports:
            - containerPort: 3000
              name: http
