apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v1
  namespace: exercises
  labels:
    app: greeter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: greeter
          image: greeter:5.3
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "v1"
            - name: GREETING
              value: "hello"
          ports:
            - containerPort: 8080
              name: http
