apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-storage
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: jouni609/log-output-writer:4.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: jouni609/log-output-reader:4.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: PINGPONG_URL
              value: "http://pingpong-svc:2345/pongs"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthprobe
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
