apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: todo-backend-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "10m"
              memory: "80Mi"
            limits:
              cpu: "150m"
              memory: "200Mi"
